# 所有工具的描述
TOOL_LIST = {
    "get-current-date": "获取当前日期",
    "get-stations-code-in-city": "查询火车站名称",
    "get-station-code-of-citys": "查询城市的 station_code",
    "get-station-code-by-names": "根据车站名查询其 station_code 和车站名",
    "get-station-by-telecode": "通过 station_telecode 查询车站的详细信息",
    "get-tickets": "查询高铁/火车信息",
    "get-interline-tickets": "查询中转高铁/火车信息",
    "get-train-route-stations": "查询列车途径车站及详细经停信息",
    "maps_regeocode": "将经纬度坐标转换为行政区划地址信息",
    "maps_geo": "将结构化地址转换为经纬度坐标",
    "maps_ip_location": "IP 定位",
    "maps_weather": "查询城市天气",
    "maps_search_detail": "查询关键词 POI ID 的详细信息",
    "maps_bicycling": "骑行方案规划",
    "maps_direction_walking": "100km 内步行方案规划",
    "maps_direction_driving": "小客车出行方案规划",
    "maps_direction_transit_integrated": "公共交通方案规划",
    "maps_distance": "测量两点间距离",
    "maps_text_search": "关键词搜索 POI",
    "maps_around_search": "搜索周边城市",
    "bailian_web_search": "搜索景点数据",
    "relative-date": "查询日期",
    "query-weather": "查询天气",
}
